# Copyright agntcy-dir-push-action contributors
# (https://github.com/outshift-open/agntcy-dir-push-action/blob/main/CONTRIBUTORS.md)
# SPDX-License-Identifier: Apache-2.0


name: 'Set Version'
description: 'Set version from input or default commit hash'
inputs:
  version:
    description: 'Version string (defaults to git short hash)'
    required: false
outputs:
  version:
    description: 'Final version'
    value: ${{ steps.set_version.outputs.version }}
runs:
  using: 'composite'
  steps:
    - name: Set version
      id: set_version
      shell: bash
      run: |
        if [ -n "${{ inputs.version }}" ]; then
          echo "version=${{ inputs.version }}" >> $GITHUB_OUTPUT
          echo "Using provided version: ${{ inputs.version }}"
        else
          VERSION=$(git rev-parse --short HEAD)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Using git commit hash: $VERSION"
        fi