# Copyright agntcy-dir-push-action contributors
# (https://github.com/outshift-open/agntcy-dir-push-action/blob/main/CONTRIBUTORS.md)
# SPDX-License-Identifier: Apache-2.0


name: 'Verify Test Result and Upload Artifacts'
description: 'Verifies test outcomes and uploads gha artifacts'

inputs:
  verification_type:
    description: 'Type of verification (failure, success, signed_success)'
    required: true
  outcome:
    description: 'Outcome to verify'
    required: true
  test_name:
    description: 'Test name used for artifacts naming'
    required: true
  expected_error:
    description: 'Expected error message (for failure verification type)'
    required: false
  record_file:
    description: 'Record file path (for signed_success verification type)'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Run verification
      shell: bash
      run: |
        chmod +x ./test-data/verify_output.sh
        source ./test-data/verify_output.sh

        case "${{ inputs.verification_type }}" in
          "failure")
            verify_test_failure "${{ inputs.outcome }}" "${{ inputs.expected_error }}" "${{ inputs.test_name }}"
            ;;
          "success")
            verify_test_success "${{ inputs.outcome }}" "${{ inputs.test_name }}"
            ;;
          "signed_success")
            verify_test_signed_success "${{ inputs.outcome }}" "${{ inputs.test_name }}" "${{ inputs.record_file }}"
            ;;
          *)
            echo "Error: Unknown verification type: ${{ inputs.verification_type }}"
            exit 1
            ;;
        esac

    - name: Upload test artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.test_name }}-outputs
        path: /tmp/dirctl-artifacts/
        retention-days: 30
